export const COURSE_STATUS_PENDING = 'pending';
export const COURSE_STATUS_IN_PROGRESS = 'in-progress';
export const COURSE_STATUS_COMPLETE = 'complete';

export const COURSE_STATUSES = [
	COURSE_STATUS_PENDING,
	COURSE_STATUS_IN_PROGRESS,
	COURSE_STATUS_COMPLETE,
];